<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.mx</groupId>
		<artifactId>nqboard</artifactId>
		<version>${revision}</version>
	</parent>

	<artifactId>nqboard-quanta</artifactId>

	<description>nqboard 量化模块</description>
	<packaging>pom</packaging>

	<modules>
		<module>nqboard-quanta-api</module>
		<module>nqboard-quanta-biz</module>
	</modules>
</project>
